name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Publish type'
        required: true
        type: choice
        options:
          - release
          - snapshot
        default: snapshot
  push:

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check & Test
        uses: gradle/gradle-build-action@v2
        with:
          distributions-cache-enabled: true
          configuration-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: |
            check
            test
            --stacktrace
            --scan

      - name: Clean project
        run: ./gradlew clean

  publish:
    name: Publishing
    needs: build
    runs-on: ubuntu-latest
    # Only publish on main branch
    if: github.ref == 'refs/heads/main'

    env:
      RELEASE: ${{ github.event.inputs.type == 'release' }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish publications
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --stacktrace
